/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Herif.Program;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 
/**
 *
 * @author Be Humble
 */
public class Formtransaksi extends javax.swing.JFrame {
    
    public Connection conn;
   public Statement cn;
   Statement stat;
    ResultSet rs;
    
    
    public void koneksi(){
         try {
             Class.forName("com.mysql.jdbc.Driver");
             conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
             cn=conn.createStatement();
             
                     }
         catch(ClassNotFoundException | SQLException e) {
             JOptionPane.showMessageDialog(null,"koneksi gagal. . ."+e);
             System.out.println(e.getMessage());
         }
     }
    
    private void kosongkan_form(){
       txtno.setEditable(true);
       cnama.setSelectedItem("");
        txtjumlahpenerima.setText(null);
        txtnamapabrik.setText(null);
        txttglterima.setText(null);
        cbinstansi.setSelectedItem("");
        txtjmldistribusi.setText("");
        txttglkadaluarsa.setText("");
        txtstock.setText("");
        
        
      //  txtno.setVisible(null);
        
    }

     private void no_otomatis (){
            try{
        stat = conn.createStatement();
        String sql = "select max(no) from transaksi";
        rs = stat.executeQuery(sql);
         while(rs.next()){
             int a = rs.getInt(1);
            txtno.setText("00"+Integer.toString(a+1));
   
        }}
        catch (Exception ex){
        }
    }
     public void obat(){
        try{
        koneksi();
        String sql="select*from db_input1";
        ResultSet rs=cn.executeQuery(sql);
        while(rs.next()){
        cnama.addItem(rs.getString("Nm_Obat"));
        }
        }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Ada kesalahan koneksi"+ e);
        }
   }
     
      public void instansi(){
        try{
        koneksi();
        String sql="select*from db_input2";
        ResultSet rs=cn.executeQuery(sql);
        while(rs.next()){
        cbinstansi.addItem(rs.getString("Nama_Instansi"));
        }
        }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Ada kesalahan koneksi"+ e);
        }
   }
  
      
      
      public void curentdate(){  
        Calendar cal = new GregorianCalendar();  
        int year=cal.get(Calendar.YEAR);  
        int month=cal.get(Calendar.MONTH);  
        int day=cal.get(Calendar.DAY_OF_MONTH);  
        
        txttgl.setText(year+"/"+(month+1)+"/"+day); 
   }
      
      
       private void tampilkan_data(){
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("No");
        table.addColumn("Kode Obat");
        table.addColumn("Nama Instansi");
        table.addColumn("Tanggal");
        table.addColumn("Stock");
           
        try{
             koneksi();
             String sql = "select * from transaksi order by no asc";
             ResultSet rs=cn.executeQuery(sql);
             while(rs.next())
             {
                 table.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),
                     rs.getString(4),rs.getString(5)});
                 
             }
             tabel.setModel(table);
             }catch (Exception e){
                 JOptionPane.showMessageDialog(null,"Ada Kesalahan");
             }
        
    }
    /**
     * Creates new form Form1
     */
    public Formtransaksi() {
        initComponents();
        kosongkan_form();
        obat();
        instansi();
        no_otomatis();
        curentdate();
        tampilkan_data();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttgl = new javax.swing.JTextField();
        txtjumlahpenerima = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnamapabrik = new javax.swing.JTextField();
        txttglterima = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbinstansi = new javax.swing.JComboBox<>();
        cnama = new javax.swing.JComboBox<>();
        btAdd = new javax.swing.JButton();
        btOut = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtjmldistribusi = new javax.swing.JTextField();
        txttglkadaluarsa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Data Input");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("DATA TRANSAKSI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 16, 224, 39));

        jLabel2.setText("Nomor Transaksi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 64, 122, 31));
        getContentPane().add(txtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 64, 116, 31));

        jLabel3.setText("Nama Obat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 111, 122, 31));
        getContentPane().add(txttgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 116, 31));
        getContentPane().add(txtjumlahpenerima, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 116, 31));

        jLabel4.setText("Jumlah Penerimaan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 151, 140, 31));

        jLabel5.setText("Nama Pabrik");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 192, 122, 31));

        txtnamapabrik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamapabrikActionPerformed(evt);
            }
        });
        getContentPane().add(txtnamapabrik, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 192, 116, 31));
        getContentPane().add(txttglterima, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 232, 116, 31));

        jLabel6.setText("Tanggal Diterima");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 232, 122, 31));

        jLabel7.setText("Nama Instansi");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 64, 122, 31));

        jLabel8.setText("Jumlah Distribusi");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 104, 122, 31));

        cbinstansi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbinstansiActionPerformed(evt);
            }
        });
        getContentPane().add(cbinstansi, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 64, 136, 31));

        cnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnamaActionPerformed(evt);
            }
        });
        getContentPane().add(cnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 136, 31));

        btAdd.setText("SAVE");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        getContentPane().add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 180, 100, 32));

        btOut.setText("OUT");
        btOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOutActionPerformed(evt);
            }
        });
        getContentPane().add(btOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 110, 30));

        jLabel10.setText("Stock");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 86, -1));
        getContentPane().add(txtjmldistribusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 134, -1));

        txttglkadaluarsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttglkadaluarsaActionPerformed(evt);
            }
        });
        getContentPane().add(txttglkadaluarsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 156, 120, 30));

        jLabel11.setText("Tangal Kadaluarsa");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 140, -1));
        getContentPane().add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 90, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Obat", "Kode Instansi", "Tanggal", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 660, 150));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamapabrikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamapabrikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamapabrikActionPerformed

    private void btOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOutActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btOutActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
    try{
        String sql = "INSERT INTO transaksi VALUES ('"+txtno.getText()+"','"+cnama.getSelectedItem()+"','"+cbinstansi.getSelectedItem()+"','"+txttgl.getText()+"','"+txtstock.getText()+"')";
        java.sql.Connection conn = (Connection)Konfig.configDB();
        java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
        pstm.execute();
        JOptionPane.showMessageDialog(null, "Proses Simpan data Berhasil..");
               kosongkan_form();
    }catch(HeadlessException | SQLException e){
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btAddActionPerformed

    private void txttglkadaluarsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttglkadaluarsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttglkadaluarsaActionPerformed

    private void cnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnamaActionPerformed
 try{
            koneksi();
            String sql = "Select* from db_input1 where Nm_Obat='"+cnama.getSelectedItem()+"'";
            ResultSet rs=cn.executeQuery(sql);
            while(rs.next())
            {
                txtjumlahpenerima.setText(""+rs.getString("Jml_Diterima"));
                txtnamapabrik.setText(""+rs.getString("Nm_Pabrik"));
                txttglterima.setText(""+rs.getString("Tgl_Terima"));
              
            }
        }catch(Exception e){
        }     // TODO add your handling code here:
    }//GEN-LAST:event_cnamaActionPerformed

    private void cbinstansiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbinstansiActionPerformed
try{
            koneksi();
            String sql = "Select* from db_input2 where Nama_Instansi='"+cbinstansi.getSelectedItem()+"'";
            ResultSet rs=cn.executeQuery(sql);
            while(rs.next())
            {
                txtjmldistribusi.setText(""+rs.getString("Jml_Didistribusi"));
                txttglkadaluarsa.setText(""+rs.getString("Tgl_Kadarluarsa"));
                           
            }
        }catch(Exception e){
        }          // TODO add your handling code here:
    }//GEN-LAST:event_cbinstansiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formtransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btOut;
    private javax.swing.JComboBox<String> cbinstansi;
    private javax.swing.JComboBox<String> cnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txtjmldistribusi;
    private javax.swing.JTextField txtjumlahpenerima;
    private javax.swing.JTextField txtnamapabrik;
    private javax.swing.JTextField txtno;
    private javax.swing.JTextField txtstock;
    private javax.swing.JTextField txttgl;
    private javax.swing.JTextField txttglkadaluarsa;
    private javax.swing.JTextField txttglterima;
    // End of variables declaration//GEN-END:variables
}
